### ISSUE TITLE
Initial window size

### ISSUE THREAD

**Issue by timtas** [SKefalidis/xfce4-alsamixer#6]
Great, I can already build and run your port, will pull your changes from time to time and maybe add some remarks...

My first remark is the same I had with the original gtk-alsamixer: The initial window size is too small. I have set it to 800x400, which usually seems to be fine.

**Comment by SKefalidis** [comment]
Great! 

#3 is related, there seems to have been an attempt to make the app remember the size of the window, so I'll probably add that as an option after I port it to GTK 3

**Comment by SKefalidis** [comment]
Fixed in 8b002b68cfc1e2b469a05e8a80764e41ef4588e8
